// ============================================
// App Constants
// ============================================

const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CHILD: 'CHILD',
  PARENT: 'PARENT',
  TEACHER: 'TEACHER',
  SCHOOL: 'SCHOOL',
};

const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DELETED: 'DELETED',
};

const MEMBERSHIP_LEVELS = {
  BRONZE: 'BRONZE',
  SILVER: 'SILVER',
  GOLD: 'GOLD',
  PLATINUM: 'PLATINUM',
};

const CONTENT_TYPES = {
  VIDEO: 'VIDEO',
  BOOK_STORY: 'BOOK_STORY',
  SONG: 'SONG',
  GAME: 'GAME',
};

const CONTENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const POINTS_TRANSACTION_TYPES = {
  EARNED: 'EARNED',
  REDEEMED: 'REDEEMED',
  EXPIRED: 'EXPIRED',
  ADMIN_ADD: 'ADMIN_ADD',
  ADMIN_DEDUCT: 'ADMIN_DEDUCT',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
  SIGNUP_BONUS: 'SIGNUP_BONUS',
};

const NOTIFICATION_TYPES = {
  ORDER_UPDATE: 'ORDER_UPDATE',
  POINTS_UPDATE: 'POINTS_UPDATE',
  NEW_CONTENT: 'NEW_CONTENT',
  SYSTEM: 'SYSTEM',
  PROMO: 'PROMO',
  REFERRAL: 'REFERRAL',
};

const BANNER_TYPES = {
  HOME: 'HOME',
  PROMO: 'PROMO',
  SEASONAL: 'SEASONAL',
  CAMPAIGN: 'CAMPAIGN',
};

const MOBILE_ROLES = [USER_ROLES.CHILD, USER_ROLES.PARENT, USER_ROLES.TEACHER, USER_ROLES.SCHOOL];
const ADMIN_ROLES = [USER_ROLES.SUPER_ADMIN];
const ALL_ROLES = [...ADMIN_ROLES, ...MOBILE_ROLES];

module.exports = {
  USER_ROLES,
  ACCOUNT_STATUS,
  MEMBERSHIP_LEVELS,
  CONTENT_TYPES,
  CONTENT_STATUS,
  ORDER_STATUS,
  POINTS_TRANSACTION_TYPES,
  NOTIFICATION_TYPES,
  BANNER_TYPES,
  MOBILE_ROLES,
  ADMIN_ROLES,
  ALL_ROLES,
};

